### ISSUE TITLE
docker pushが落ちている

### ISSUE THREAD

**Issue by KisaragiEffective** [GiganticMinecraft/chunk-search-rs#30]
https://github.com/GiganticMinecraft/chunk-search-rs/runs/6938429955?check_suite_focus=true#step:5:109

**Comment by kory33** [comment]
Fixed by #28

**Comment by Lucky3028** [comment]
Dockerfileの中でのbuildでまだprotocがないからぶっ壊れていますね...

**Comment by Lucky3028** [comment]
これ、build.rsで生成したsrc/protos/*.rsをgitの管理下に置くっていうのではダメなんですか？ @kory33

**Comment by KisaragiEffective** [comment]
直ってそう
